# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev2-trybs',
                'doc_host': 'https://bsalanie.github.io',
                'git_url': 'https://github.com/bsalanie/nbdev2-trybs',
                'lib_path': 'nbdev2_trybs'},
  'syms': { 'nbdev2_trybs.card': { 'nbdev2_trybs.card.Card': ('index.html#card', 'nbdev2_trybs/card.py'),
                                   'nbdev2_trybs.card.Card.__eq__': ('index.html#card.__eq__', 'nbdev2_trybs/card.py'),
                                   'nbdev2_trybs.card.Card.__gt__': ('index.html#card.__gt__', 'nbdev2_trybs/card.py'),
                                   'nbdev2_trybs.card.Card.__init__': ('index.html#card.__init__', 'nbdev2_trybs/card.py'),
                                   'nbdev2_trybs.card.Card.__lt__': ('index.html#card.__lt__', 'nbdev2_trybs/card.py'),
                                   'nbdev2_trybs.card.Card.__str__': ('index.html#card.__str__', 'nbdev2_trybs/card.py')}}}