# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/index.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/index.ipynb 1
from fastcore.utils import *



# %% ../nbs/index.ipynb 9
suits = ['Trefle', 'Carreau', 'Coeur', 'Pique']

# %% ../nbs/index.ipynb 10
ranks = [str(i) for i in range(2, 11)] + ['Valet', 'Dame', 'Roi', 'As']

# %% ../nbs/index.ipynb 11
class Card:
    " A playing card"
    def __init__(self, 
                 suit: int,    # an integer index into `suits`
                 rank: int     # an integer index into `ranks`
                ):
        self.suit, self.rank = suit, rank
    def __eq__(self, a_card):
        return ((self.suit, self.rank) == (a_card.suit, a_card.rank))
       
    def __str__(self):
        return f'{ranks[self.rank]} de {suits[self.suit]}'
    __repr__ = __str__


# %% ../nbs/index.ipynb 19
@patch
def __lt__(self: Card, b: Card): return (self.suit, self.rank) < (b.suit, b.rank)

# %% ../nbs/index.ipynb 20
@patch
def __gt__(self: Card, b: Card): return (self.suit, self.rank) > (b.suit, b.rank)
